
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.216157
  longitude: 8.625875

logger:
  default: error
  logs:
    custom_components.dwd_weather: debug
    #custom_components.spotcast: debug

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ::1
