name: Get debug infos

on:
  issue_comment:
    types: [created]

jobs:
  debug-info:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    # correct author, correct command prefix
    if: |
      github.event.comment.user.login == 'FL550' &&
      startsWith(github.event.comment.body, '/debug ')

    steps:
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-tk
            pip install --cache-dir ~/.cache/pip -r .github/requirements.txt
      - name: checkout repo
        uses: actions/checkout@v4
      #  extract the argument (everything after "/debug ")
      - id: parse
        run: |
          STATION=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
          MODE=$(echo "${{ github.event.comment.body }}" | awk '{print $3}')
          echo "station=$STATION" >> "$GITHUB_OUTPUT"
          echo "mode=$MODE" >> "$GITHUB_OUTPUT"
      # use the extracted value
      - name: fetch weather
        id: run
        env:
          STATION: ${{ steps.parse.outputs.station }}
        run: |
            python .github/scripts/get_station_data.py > result.txt
            echo "stdout=result.txt" >> "$GITHUB_OUTPUT"

      - name: parse_result
        id: parse_result
        run: |
            # --- build the folded markdown ---
            RAW="$(cat ${{ steps.run.outputs.stdout }})"

            # Extract station info (first two lines)
            STATION_LINE=$(echo "$RAW" | grep '^Station:')
            INFO_LINE=$(echo "$RAW" | grep "{" | head -n1)

            # Extract forecast header and table (everything after the station info)
            FORECAST_HEADER=$(echo "$RAW" | grep '^Forecast')
            FORECAST_TABLE=$(echo "$RAW" | awk '/^\|/{print}' | sed ':a;N;$!ba;s/\n/\\n/g')

            BODY=$(cat <<EOF
            <details>
            <summary>$STATION_LINE</summary>

            \`\`\`python
            $INFO_LINE
            \`\`\`
            </details>

            <details>
            <summary>$FORECAST_HEADER</summary>

            $(echo -e "$FORECAST_TABLE")

            </details>
            EOF
            )

            # expose BODY as a step output for downstream steps
            echo "body<<EOF" >> "$GITHUB_OUTPUT"
            echo "$BODY" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Update comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          comment-id: ${{ github.event.comment.id }}
          edit-mode: replace
          body: "${{ steps.parse_result.outputs.body }}"
