---
name: "Python testing"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Test package"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Cache pip"
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          # Prefer requirements-test.txt
          if [ -f requirements-test.txt ]; then
            bin/install_requirements requirements-test.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          elif [ -f requirements-dev.txt ]; then
            bin/install_requirements requirements-dev.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          elif [ -f requirements.txt ]; then
            bin/install_requirements requirements.txt "${{ secrets.ADMIN_GITHUB_TOKEN }}"
          fi
          pip install pytest-xdist

          if [ -d custom_components ]; then
            echo '"""Stub."""' >custom_components/__init__.py
          fi

      - name: "Run tests with pytest"
        if: matrix.python-version != '3.9'
        run: |
          pytest --basetemp=$RUNNER_TEMP --durations=10 -n auto --dist=loadfile -qq -o console_output_style=count -p no:sugar --asyncio-mode=auto
          ./bin/check_dirty
