name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest
        python-version: ["3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Home Assistant and integration
        run: |
          ./scripts/setup

      - name: Run test suite
        run: pytest -x --tb=short
